In [1]:
top={'black_none_longsleeve','white_none_longsleeve','blue_none_longsleeve','red_none_longsleeve','gray_none_longsleeve','yellow_none_longsleeve','khaki_none_longsleeve', 'beige_none_longsleeve','pink_none_longsleeve', 'purple_none_longsleeve',
'black_none_longshirt','white_none_longshirt','gray_none_longshirt','beige_none_longshirt',
'black_none_longneat', 'white_none_longneat', 'gray_none_longneat', 'beige_none_longneat',
'black_none_shortsleeve','white_none_shortsleeve', 'blue_none_shortsleeve','red_none_shortsleeve','gray_none_shortsleeve','yellow_none_shortsleeve','khaki_none_shortsleeve','beige_none_shortsleeve','pink_none_shortsleeve','purple_none_shortsleeve',
'cnone_flower_longshirt','cnone_flower_shortshirt',
'black_stripe_longsleeve','red_stripe_longsleeve','yellow_stripe_longsleeve',
'black_stripe_shortsleeve','red_stripe_shortsleeve','yellow_stripe_shortsleeve',
'black_check_longshirt','blue_check_longshirt','red_check_longshirt','yellow_check_longshirt',
'black_check_shortshirt','blue_check_shortshirt','red_check_shortshirt','yellow_check_shortshirt',
'black_nike_longsleeve','white_nike_longsleeve',
'black_nike_shortsleeve','white_nike_shortsleeve',
'black_none_sleeveless','white_none_sleeveless'
}
print("top: ",len(top))

bottom={'black_none_longpants','white_none_longpants','lightblue_none_longpants','blue_none_longpants','gray_none_longpants','beige_none_longpants',
'black_none_shortpants','white_none_shortpants','lightblue_none_shortpants','blue_none_shortpants','gray_none_shortpants','beige_none_shortpants','red_none_shortpants',
'black_none_longskirt','white_none_longskirt','lightblue_none_longskirt','blue_none_longskirt','beige_none_longskirt',
'black_none_shortskirt','white_none_shortskirt','lightblue_none_shortskirt','blue_none_shortskirt','beige_none_shortskirt',
'black_none_adidaslongpants','black_none_adidasshortpants','black_none_joggerpants'
}
print("bottom: ",len(bottom))

dress={'black_none_sumlongdress','white_none_sumlongdress','blue_none_sumlongdress','red_none_sumlongdress','beige_none_sumlongdress',
'black_none_sumshortdress','white_none_sumshortdress','blue_none_sumshortdress','red_none_sumshortdress','beige_none_sumshortdress',
'black_none_winlongdress','white_none_winlongdress','blue_none_winlongdress','red_none_winlongdress','beige_none_winlongdress',
'black_none_winshortdress','white_none_winshortdress','blue_none_winshortdress','red_none_winshortdress','beige_none_winshortdress'
}
print("dress: ",len(dress))

outer={'black_none_cardigan','gray_none_cardigan','brown_none_cardigan',
'black_none_hoodie','gray_none_hoodie','brown_none_hoodie',
'black_none_coat','gray_none_coat','brown_none_coat',
'black_none_ma1','khaki_none_ma1',
'black_none_blazer','gray_none_blazer',
'blue_none_jacket','black_none_riderjacket',
'black_none_parka','white_none_parka',
'black_none_neatvest','gray_none_neatvest',
}
print("outer: ",len(outer))

top:  50
bottom:  26
dress:  20
outer:  19

In [2]:
# 남자: ['campus', 'casual', 'modern', 'office', 'simple', 'travel']
m_vector={
    'flower_longshirt': [1, 25, 12, 2, 1, 60],
    'flower_shortshirt': [1, 9, 0, 1, 2, 18],
    'none_longneat': [31, 43, 13, 4, 54, 2],
    'none_longsleeve': [78, 108, 18, 5, 50, 15],
    'none_shortsleeve': [12, 15, 1, 1, 5, 2],
    'check_longshirt': [38, 36, 20, 23, 19, 5],
    'check_shortshirt': [15, 15, 3, 1, 3, 0],
    'stripe_longsleeve': [32, 51, 12, 0, 39, 8],
    'stripe_shortsleeve': [13, 16, 1, 1, 4, 0],
    'nike_longsleeve': [29, 50, 7, 2, 36, 13],
    'nike_shortsleeve': [6, 16, 0, 2, 4, 7],
    'none_sleeveless': [3, 9, 0, 1, 2, 14],
    'none_longshirt': [14, 14, 44, 35, 31, 4],
    'none_longpants': [49, 56, 63, 87, 82, 7],
    'adidaslongpants':[7, 47, 5, 2, 33, 26],
    'joggerpants': [29, 49, 17, 3, 13, 13],
    'none_shortpants': [7, 15, 1, 2, 4, 2],
    'adidasshortpants':[3, 48, 3, 1, 25, 32],
    'blue_none_longpants': [42, 53, 10, 6, 37, 10],
    'blazer': [12, 21, 39, 57, 29, 2],
    'coat': [24, 18, 40, 32, 39, 5],
    'riderjacket': [19, 30, 52, 5, 8, 11],
    'ma1': [38, 50, 13, 3, 22, 11],
    'jacket': [17, 5, 1, 1, 4, 0],
    'cardigan': [35, 39, 13, 17, 48, 3],
    'hoodie': [6, 17, 0, 1, 3, 1],
    'parka': [5, 14, 1, 3, 3, 1],
    'neatvest': [18, 16, 6, 5, 23, 0]
}

In [3]:
# 여자: ['campus', 'casual', 'femi', 'lovely', 'modern', 'ofice', 'simple', 'travel']
w_vector={
    'check_longshirt': [42, 47, 2, 2, 2, 0, 30, 11],
    'flower_longshirt': [24, 4, 26, 58, 0, 4, 0, 12],
    'none_longsleeve': [51, 83, 13, 6, 14, 2, 85, 32],
    'stripe_longsleeve': [42, 49, 1, 4, 5, 0, 43, 9],
    'none_longneat': [29, 37, 3, 7, 12, 2, 39, 5],
    'none_longshirt': [8, 11, 19, 9, 20, 51, 38, 2],
    'nike_longsleeve': [8, 50, 3, 1, 12, 0, 24, 18],
    'none_sleeveless': [1, 7, 8, 6, 5, 0, 11, 11],
    'none_shortsleeve': [17, 30, 2, 8, 3, 3, 35, 4],
    'nike_shortsleeve': [2, 19, 0, 0, 2, 0, 6, 11],
    'flower_shortshirt': [5, 5, 8, 19, 0, 0, 1, 6],
    'stripe_shortsleeve': [11, 8, 0, 2, 3, 3, 21, 0],
    'check_shortshirt': [4, 5, 10, 22, 0, 0, 3, 4],
    'adidaslongpants': [15, 49, 0, 0, 5, 1, 24, 17],
    'joggerpants': [16, 48, 1, 1, 15, 0, 35, 9],
    'none_longpants': [65, 32, 21, 3, 51, 95, 82, 7], # white, black, beige, gray
    'lightblue_none_longpants': [48, 47, 2, 3, 4, 2, 35, 15], # lightblue, blue
    'blue_none_longpants': [48, 47, 2, 3, 4, 2, 35, 15],
    'longskirt': [25, 22, 16, 20, 11, 18, 41, 19],
    'adidasshortpants': [2, 17, 0, 1, 0, 0, 9, 8],
    'none_shortpants': [4, 6, 4, 2, 3, 3, 17, 1],
    'shortskirt': [14, 6, 1, 5, 1, 3, 12, 1],
    'lightblue_none_shortpants': [9, 16, 0, 2, 0, 0, 11, 4], #blue
    'winlongdress': [4, 6, 20, 4, 26, 41, 22, 4],
    'winshortdress': [6, 4, 29, 17, 25, 38, 10, 5],
    'sumlongdress': [4, 8, 9, 6, 2, 5, 4, 6],
    'sumshortdress': [3, 5, 7, 3, 11, 5, 8, 3],
    'parka': [5, 19, 1, 0, 0, 1, 6, 4],
    'riderjacket': [11, 11, 0, 2, 17, 0, 4, 1],
    'neatvest': [13, 14, 0, 0, 1, 5, 8, 1],
    'jacket': [17, 19, 0, 0, 1, 0, 4, 1],
    'blazer': [17, 25, 6, 1, 23, 24, 35, 7],
    'hoodie': [40, 46, 2, 0, 1, 0, 31, 19],
    'coat': [11, 8, 26, 23, 26, 29, 15, 6],
    'cardigan': [30, 35, 9, 32, 2, 3, 35, 10],
    'ma1': [30, 44, 2, 1, 11, 1, 14, 26]
}

In [4]:
# import pandas as pd
# from sklearn import preprocessing

# 정규화
def norm(v, key):
    c = v[key]
    v_min = c.min()
    v_max = c.max()
    v[key] = (c-v_min)/(v_max-v_min)

In [5]:
import pandas as pd
from sklearn import preprocessing
import numpy as np

df = pd.DataFrame(w_vector)

for i in df.columns.tolist():
    norm(df,i)
df

,check_longshirt,flower_longshirt,none_longsleeve,stripe_longsleeve,none_longneat,none_longshirt,nike_longsleeve,none_sleeveless,none_shortsleeve,nike_shortsleeve,...,sumshortdress,parka,riderjacket,neatvest,jacket,blazer,hoodie,coat,cardigan,ma1
0,0.893617,0.413793,0.590361,0.857143,0.729730,0.122449,0.16,0.090909,0.454545,0.105263,...,0.000,0.263158,0.647059,0.928571,0.894737,0.470588,0.869565,0.217391,0.848485,0.674419
1,1.000000,0.068966,0.975904,1.000000,0.945946,0.183673,1.00,0.636364,0.848485,1.000000,...,0.250,1.000000,0.647059,1.000000,1.000000,0.705882,1.000000,0.086957,1.000000,1.000000
2,0.042553,0.448276,0.132530,0.020408,0.027027,0.346939,0.06,0.727273,0.000000,0.000000,...,0.500,0.052632,0.000000,0.000000,0.000000,0.147059,0.043478,0.869565,0.212121,0.023256
3,0.042553,1.000000,0.048193,0.081633,0.135135,0.142857,0.02,0.545455,0.181818,0.000000,...,0.000,0.000000,0.117647,0.000000,0.000000,0.000000,0.000000,0.739130,0.909091,0.000000
4,0.042553,0.000000,0.144578,0.102041,0.270270,0.367347,0.24,0.454545,0.030303,0.105263,...,1.000,0.000000,1.000000,0.071429,0.052632,0.647059,0.021739,0.869565,0.000000,0.232558
5,0.000000,0.068966,0.000000,0.000000,0.000000,1.000000,0.00,0.000000,0.030303,0.000000,...,0.250,0.052632,0.000000,0.357143,0.000000,0.676471,0.000000,1.000000,0.030303,0.000000
6,0.638298,0.000000,1.000000,0.877551,1.000000,0.734694,0.48,1.000000,1.000000,0.315789,...,0.625,0.315789,0.235294,0.571429,0.210526,1.000000,0.673913,0.391304,1.000000,0.302326
7,0.234043,0.206897,0.361446,0.183673,0.081081,0.000000,0.36,1.000000,0.060606,0.578947,...,0.000,0.210526,0.058824,0.071429,0.052632,0.176471,0.413043,0.000000,0.242424,0.581395

In [6]:
import pandas as pd
df2 = pd.DataFrame(m_vector)
for i in df2.columns.values.tolist():
    norm(df2, i)

df2

,flower_longshirt,flower_shortshirt,none_longneat,none_longsleeve,none_shortsleeve,check_longshirt,check_shortshirt,stripe_longsleeve,stripe_shortsleeve,nike_longsleeve,...,blue_none_longpants,blazer,coat,riderjacket,ma1,jacket,cardigan,hoodie,parka,neatvest
0,0.000000,0.055556,0.557692,0.708738,0.785714,1.000000,1.000000,0.627451,0.8125,0.562500,...,0.765957,0.181818,0.542857,0.297872,0.744681,1.000000,0.711111,0.352941,0.307692,0.782609
1,0.406780,0.500000,0.788462,1.000000,1.000000,0.939394,1.000000,1.000000,1.0000,1.000000,...,1.000000,0.345455,0.371429,0.531915,1.000000,0.294118,0.800000,1.000000,1.000000,0.695652
2,0.186441,0.000000,0.211538,0.126214,0.000000,0.454545,0.200000,0.235294,0.0625,0.104167,...,0.085106,0.672727,1.000000,1.000000,0.212766,0.058824,0.222222,0.000000,0.000000,0.260870
3,0.016949,0.055556,0.038462,0.000000,0.000000,0.545455,0.066667,0.000000,0.0625,0.000000,...,0.000000,1.000000,0.771429,0.000000,0.000000,0.058824,0.311111,0.058824,0.153846,0.217391
4,0.000000,0.111111,1.000000,0.436893,0.285714,0.424242,0.200000,0.764706,0.2500,0.708333,...,0.659574,0.490909,0.971429,0.063830,0.404255,0.235294,1.000000,0.176471,0.153846,1.000000
5,1.000000,1.000000,0.000000,0.097087,0.071429,0.000000,0.000000,0.156863,0.0000,0.229167,...,0.085106,0.000000,0.000000,0.127660,0.170213,0.000000,0.000000,0.058824,0.000000,0.000000

In [7]:
top1=pd.DataFrame()
bottom1=pd.DataFrame()
dress1=pd.DataFrame()
outer1=pd.DataFrame()

In [8]:
for i in top:
    if 'check_longshirt' in i:
        top1[i] = df2['check_longshirt'].values.tolist()
    elif 'flower_longshirt' in i:
        top1[i] = df2['flower_longshirt'].values.tolist()
    elif 'none_longsleeve' in i:
        top1[i] = df2['none_longsleeve'].values.tolist()
    elif 'stripe_longsleeve' in i:
        top1[i] = df2['stripe_longsleeve'].values.tolist()
    elif 'none_longneat' in i:
        top1[i] = df2['none_longneat'].values.tolist()
    elif 'none_longshirt' in i:
        top1[i] = df2['none_longshirt'].values.tolist()
    elif 'nike_longsleeve' in i:
        top1[i] = df2['nike_longsleeve'].values.tolist()
    elif 'none_sleeveless' in i:
        top1[i] = df2['none_sleeveless'].values.tolist()
    elif 'none_shortsleeve' in i:
        top1[i] = df2['none_shortsleeve'].values.tolist()
    elif 'nike_shortsleeve' in i:
        top1[i] = df2['nike_shortsleeve'].values.tolist()
    elif 'flower_shortshirt' in i:
        top1[i] = df2['flower_shortshirt'].values.tolist()
    elif 'stripe_shortsleeve' in i:
        top1[i] = df2['stripe_shortsleeve'].values.tolist()
    elif 'check_shortshirt' in i:
        top1[i] = df2['check_shortshirt'].values.tolist()
    else:
        pass
top1

,purple_none_shortsleeve,gray_none_longneat,black_none_longneat,white_none_shortsleeve,khaki_none_longsleeve,beige_none_shortsleeve,yellow_check_longshirt,pink_none_longsleeve,beige_none_longshirt,cnone_flower_longshirt,...,black_none_longshirt,beige_none_longneat,cnone_flower_shortshirt,pink_none_shortsleeve,gray_none_longshirt,blue_check_longshirt,purple_none_longsleeve,black_stripe_shortsleeve,blue_check_shortshirt,black_check_longshirt
0,0.785714,0.557692,0.557692,0.785714,0.708738,0.785714,1.000000,0.708738,0.250,0.000000,...,0.250,0.557692,0.055556,0.785714,0.250,1.000000,0.708738,0.8125,1.000000,1.000000
1,1.000000,0.788462,0.788462,1.000000,1.000000,1.000000,0.939394,1.000000,0.250,0.406780,...,0.250,0.788462,0.500000,1.000000,0.250,0.939394,1.000000,1.0000,1.000000,0.939394
2,0.000000,0.211538,0.211538,0.000000,0.126214,0.000000,0.454545,0.126214,1.000,0.186441,...,1.000,0.211538,0.000000,0.000000,1.000,0.454545,0.126214,0.0625,0.200000,0.454545
3,0.000000,0.038462,0.038462,0.000000,0.000000,0.000000,0.545455,0.000000,0.775,0.016949,...,0.775,0.038462,0.055556,0.000000,0.775,0.545455,0.000000,0.0625,0.066667,0.545455
4,0.285714,1.000000,1.000000,0.285714,0.436893,0.285714,0.424242,0.436893,0.675,0.000000,...,0.675,1.000000,0.111111,0.285714,0.675,0.424242,0.436893,0.2500,0.200000,0.424242
5,0.071429,0.000000,0.000000,0.071429,0.097087,0.071429,0.000000,0.097087,0.000,1.000000,...,0.000,0.000000,1.000000,0.071429,0.000,0.000000,0.097087,0.0000,0.000000,0.000000

In [10]:
for i in bottom:
    if 'adidaslongpants' in i:
        bottom1[i] = df2['adidaslongpants'].values.tolist()
    elif 'joggerpants' in i:
        bottom1[i] = df2['joggerpants'].values.tolist()
    elif 'none_longpants' in i:
        if 'lightblue' in i or 'blue' in i:
            bottom1[i] = df2['blue_none_longpants'].values.tolist()
        else:
            bottom1[i] = df2['none_longpants'].values.tolist()
#     elif 'longskirt' in i:
#         bottom1[i] = df['longskirt'].values.tolist()
    elif 'adidasshortpants' in i:
        bottom1[i] = df2['adidasshortpants'].values.tolist()
    elif 'none_shortpants' in i:
        bottom1[i] = df2['none_shortpants'].values.tolist()
#         if 'lightblue' in i or 'blue' in i:
#             bottom1[i] = df2['lightblue_none_shortpants'].values.tolist()
#         else:
#             bottom1[i] = df2['none_shortpants'].values.tolist()
#     elif 'shortskirt' in i:
#         bottom1[i] = df['shortskirt'].values.tolist()
    else:
        pass
bottom1

,gray_none_shortpants,black_none_longpants,lightblue_none_shortpants,black_none_adidaslongpants,beige_none_longpants,white_none_shortpants,black_none_shortpants,lightblue_none_longpants,gray_none_longpants,white_none_longpants,blue_none_longpants,beige_none_shortpants,black_none_joggerpants,red_none_shortpants,blue_none_shortpants,black_none_adidasshortpants
0,0.428571,0.5250,0.428571,0.111111,0.5250,0.428571,0.428571,0.765957,0.5250,0.5250,0.765957,0.428571,0.565217,0.428571,0.428571,0.042553
1,1.000000,0.6125,1.000000,1.000000,0.6125,1.000000,1.000000,1.000000,0.6125,0.6125,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2,0.000000,0.7000,0.000000,0.066667,0.7000,0.000000,0.000000,0.085106,0.7000,0.7000,0.085106,0.000000,0.304348,0.000000,0.000000,0.042553
3,0.071429,1.0000,0.071429,0.000000,1.0000,0.071429,0.071429,0.000000,1.0000,1.0000,0.000000,0.071429,0.000000,0.071429,0.071429,0.000000
4,0.214286,0.9375,0.214286,0.688889,0.9375,0.214286,0.214286,0.659574,0.9375,0.9375,0.659574,0.214286,0.217391,0.214286,0.214286,0.510638
5,0.071429,0.0000,0.071429,0.533333,0.0000,0.071429,0.071429,0.085106,0.0000,0.0000,0.085106,0.071429,0.217391,0.071429,0.071429,0.659574

In [11]:
for i in dress:
    if 'winlongdress' in i:
        dress1[i] = df['winlongdress'].values.tolist()
    elif 'winshortdress' in i:
        dress1[i] = df['winshortdress'].values.tolist()
    elif 'sumlongdress' in i:
        dress1[i] = df['sumlongdress'].values.tolist()
    elif 'sumshortdress' in i:
        dress1[i] = df['sumshortdress'].values.tolist()
    else:
        pass
dress1

,red_none_sumlongdress,blue_none_sumshortdress,blue_none_sumlongdress,white_none_sumlongdress,red_none_sumshortdress,beige_none_sumshortdress,black_none_sumshortdress,white_none_winshortdress,white_none_sumshortdress,red_none_winlongdress,black_none_winlongdress,blue_none_winshortdress,blue_none_winlongdress,red_none_winshortdress,beige_none_sumlongdress,beige_none_winshortdress,beige_none_winlongdress,black_none_winshortdress,white_none_winlongdress,black_none_sumlongdress
0,0.285714,0.000,0.285714,0.285714,0.000,0.000,0.000,0.058824,0.000,0.000000,0.000000,0.058824,0.000000,0.058824,0.285714,0.058824,0.000000,0.058824,0.000000,0.285714
1,0.857143,0.250,0.857143,0.857143,0.250,0.250,0.250,0.000000,0.250,0.054054,0.054054,0.000000,0.054054,0.000000,0.857143,0.000000,0.054054,0.000000,0.054054,0.857143
2,1.000000,0.500,1.000000,1.000000,0.500,0.500,0.500,0.735294,0.500,0.432432,0.432432,0.735294,0.432432,0.735294,1.000000,0.735294,0.432432,0.735294,0.432432,1.000000
3,0.571429,0.000,0.571429,0.571429,0.000,0.000,0.000,0.382353,0.000,0.000000,0.000000,0.382353,0.000000,0.382353,0.571429,0.382353,0.000000,0.382353,0.000000,0.571429
4,0.000000,1.000,0.000000,0.000000,1.000,1.000,1.000,0.617647,1.000,0.594595,0.594595,0.617647,0.594595,0.617647,0.000000,0.617647,0.594595,0.617647,0.594595,0.000000
5,0.428571,0.250,0.428571,0.428571,0.250,0.250,0.250,1.000000,0.250,1.000000,1.000000,1.000000,1.000000,1.000000,0.428571,1.000000,1.000000,1.000000,1.000000,0.428571
6,0.285714,0.625,0.285714,0.285714,0.625,0.625,0.625,0.176471,0.625,0.486486,0.486486,0.176471,0.486486,0.176471,0.285714,0.176471,0.486486,0.176471,0.486486,0.285714
7,0.571429,0.000,0.571429,0.571429,0.000,0.000,0.000,0.029412,0.000,0.000000,0.000000,0.029412,0.000000,0.029412,0.571429,0.029412,0.000000,0.029412,0.000000,0.571429

In [11]:
for i in outer:
    if 'parka' in i:
        outer1[i] = df2['parka'].values.tolist()
    elif 'rider' in i:
        outer1[i] = df2['riderjacket'].values.tolist()
    elif 'rider' in i:
        outer1[i] = df2['rider'].values.tolist()
    elif 'vest' in i:
        outer1[i] = df2['neatvest'].values.tolist()
    elif 'jacket' in i:
        outer1[i] = df2['jacket'].values.tolist()
    elif 'blazer' in i:
        outer1[i] = df2['blazer'].values.tolist()
    elif 'hoodie' in i:
        outer1[i] = df2['hoodie'].values.tolist()
    elif 'coat' in i:
        outer1[i] = df2['coat'].values.tolist()
    elif 'cardigan' in i:
        outer1[i] = df2['cardigan'].values.tolist()
    elif 'ma1' in i:
        outer1[i] = df2['ma1'].values.tolist()
    else:
        pass
outer1

,brown_none_cardigan,black_none_riderjacket,black_none_parka,white_none_parka,gray_none_hoodie,black_none_coat,black_none_blazer,gray_none_coat,brown_none_coat,black_none_hoodie,khaki_none_ma1,brown_none_hoodie,black_none_neatvest,blue_none_jacket,black_none_ma1,gray_none_blazer,black_none_cardigan,gray_none_neatvest,gray_none_cardigan
0,0.711111,0.297872,0.307692,0.307692,0.352941,0.542857,0.181818,0.542857,0.542857,0.352941,0.744681,0.352941,0.782609,1.000000,0.744681,0.181818,0.711111,0.782609,0.711111
1,0.800000,0.531915,1.000000,1.000000,1.000000,0.371429,0.345455,0.371429,0.371429,1.000000,1.000000,1.000000,0.695652,0.294118,1.000000,0.345455,0.800000,0.695652,0.800000
2,0.222222,1.000000,0.000000,0.000000,0.000000,1.000000,0.672727,1.000000,1.000000,0.000000,0.212766,0.000000,0.260870,0.058824,0.212766,0.672727,0.222222,0.260870,0.222222
3,0.311111,0.000000,0.153846,0.153846,0.058824,0.771429,1.000000,0.771429,0.771429,0.058824,0.000000,0.058824,0.217391,0.058824,0.000000,1.000000,0.311111,0.217391,0.311111
4,1.000000,0.063830,0.153846,0.153846,0.176471,0.971429,0.490909,0.971429,0.971429,0.176471,0.404255,0.176471,1.000000,0.235294,0.404255,0.490909,1.000000,1.000000,1.000000
5,0.000000,0.127660,0.000000,0.000000,0.058824,0.000000,0.000000,0.000000,0.000000,0.058824,0.170213,0.058824,0.000000,0.000000,0.170213,0.000000,0.000000,0.000000,0.000000

In [12]:
top1.T.to_csv('./all_clothes_man.csv',mode='w')
bottom1.T.to_csv('./all_clothes_man.csv',mode='a')
dress1.T.to_csv('./all_clothes_man.csv',mode='a')
outer1.T.to_csv('./all_clothes_man.csv',mode='a')